### ISSUE TITLE
Tracking: Update container images for kube-rbac-proxy and kube-state-metrics

### ISSUE THREAD

**Issue by knisbet** [gravitational/gravity#2702]
### Description

**What happened**:
Customer S is worried that since `kube-rbac-proxy` and `kube-state-metrics` containers are based on an alpine linux version that may not have reliable reporting of vulnerabilities in their vulnerability database, impacts of potential vulnerabilities cannot be assessed. So they are requesting that the base container images be updated. 

Normally this would be outside of our policy for an LTS release, but since there are no new planned releases of gravity, it's likely better that we make this exception and try and replace or update the alpine version.

Tracking:
- [ ] Update the base alpine version of the releases we use of `kube-rbac-proxy` and `kube-state-metrics` and/or fork the projects so that we can do so. Alternatively, update those components to a later release if the later release uses a currently supported alpine, and the changelog looks like the component should be compatible.
- [ ] Basic sanity checks that the containers still runs / is compatible
- [ ] Port to 6.1.x
- [ ] Port to 7.0.x (Needed, but if there is a problem 6.1.x is more important)

**Comment by bernardjkim** [comment]
Patched in `7.0.36` & `6.1.52`
